theme: jekyll-theme-minimal


title: [Graphics principles cheatsheet]
description: [The landing page for the graphics principles cheatsheet github repository. A new tutorial on effective visual communication can be found here https://arxiv.org/abs/1903.09512]
