name: "Graphics principles"
title: "Graphics principles"
description: |
  Graphics principles homepage
output_dir: "."
base_url: https://graphicsprinciples.github.io
canonical_url: https://graphicsprinciples.github.io
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "Three laws"
      href: threelaws.html
    - text: "Cheat sheet"
      href: cheatsheet.html
    - text: "Tutorial"
      href: tutorial.html
    - text: "Case studies"
      href: https://graphicsprinciples.github.io/tutorial-case-studies
    - text: "QBV"
      href: qbv.html
    - text: "Blog"
      href: https://graphicsprinciples.github.io/gallery/
    - text: "Initiative"
      href: initiative.html
    - text: "Resources & references"
      href: resources.html
    - icon: fab fa-github
      href: https://github.com/GraphicsPrinciples
output: distill::distill_article





